# software build file

## universe = vanilla
## executable = /usr/bin/hostname
universe = container
container_image = docker://nipingel/casa:latest
log = track_interactive.log
output = track_interactive.out
error = track_interactive.err
Requirements=(Target.HasCHTCStaging == true)
+HasCHTCStaging=true
transfer_input_files = /home/nmpingel/software/uvcombine.tar, /home/nmpingel/software/analysis_scripts.tar, /home/nmpingel/software/phangs_imaging_scripts.tar, /home/nmpingel/LGLBS/LGLBS_Imaging/N6822_dag/feather_cubes.py
request_cpus = 1
request_memory = 10GB
request_disk = 1GB
queue
