# image_channel.sub
# script to base submission of LGLBS imaging jobs
#
# Specify the HTCondor Universe (vanilla is the default and is used
#  for almost all jobs) and your desired name of the HTCondor log file,
#  which is where HTCondor will describe what steps it takes to run 
#  your job. Wherever you see $(Cluster), HTCondor will insert the 
#  queue number assigned to this set of jobs at the time of submission.
container_image = file:///staging/nmpingel/container_images/casa_container.sif

# Specify your executable (single binary or a script that runs several
#  commands), arguments, and a files for HTCondor to store standard
#  output (or "screen output").
#  $(Process) will be a integer number for each job, starting with "0"
#  and increasing for the relevant number of jobs.

## imaging executable
executable = image_channel_config_pair.sh

src_name=M33 
ra_phase_center=01h33m50s 
dec_phase_center=30d29m37
ms_name=M33_A+B+C+D.wt_flagged_chan830.ms

arguments = $(ms_name) $(src_name) $(ra_phase_center) $(dec_phase_center)
log = $(ms_name)_clean_image.log
output = $(ms_name)_clean_image.out
error = $(ms_name)_clean_image.err

# Specify that HTCondor should transfer files to and from the
#  computer where each job runs. The last of these lines *would* be
#  used if there were any other files needed for the executable to use.
Requirements=(Target.HasCHTCStaging == true)
+HasCHTCStaging=true

# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.
transfer_input_files = image_channel_config_pair.py, image_channel_config_pair.sh
request_cpus = 6
request_memory=50GB
request_disk = 35GB

## queue 
queue 1